### ISSUE TITLE
'Place event everywhere' use cases where it doesn't work in-game should somehow be removed or shown

### ISSUE THREAD

**Issue by FawFuLJJ2** [Violet-CLM/MLLE#95]
There are 2 use cases that come to mind:

-some Event IDs simply not working
- holding x,y to snap to tile still creates a seperate event, visually identical to a 'normal event that doesn't work. For example 'one way'.

Any form of detection/organising to prevent errors here is welcome.

**Comment by Violet-CLM** [comment]
I'm guessing by "tile" in the title you mean "event."

I'm hesitant to make hard rules about which events shouldn't be placed, because behaviors can be overwritten. "One Way" creates a blaster bullet. But maybe the scriptwriter gives blaster bullets a different behavior that reacts favorably to being placed in the level. I don't know.

**Comment by FawFuLJJ2** [comment]
Event instead of tile, yeah, my bad. I understand your point and I think a lighter solution with 'shown' is preferred. It's not to be restrictive, but to be able to tell event placement styles in MLLE apart, just in case you run into scenario's of events not working because of the new method and MLLE gives no information on it. I have been thinking of 2 options:

- Give every event a little marker or different color that is placed with the new method.
- Give every event that doesn't work by default a marker or different color.
